# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.0-alpha.1
maven_group=stellarwitch7
archives_base_name=obeisance

# Publish
publish_target_min=1.21.1
publish_target_max=1.21.1
mod_github=StellarWitch7/obeisance
git_branch=main
mod_modrinth=Mpp5lxQE

# Fabric Properties
# check these on https://fabricmc.net/develop
deps.minecraft=1.21.1
deps.yarn=1.21.1+build.3
deps.floader=0.16.13

# Dependencies
deps.fabric-api=0.115.4+1.21.1
deps.owo-lib=0.12.15+1.21
deps.lavender=0.1.15+1.21
deps.cicada=0.8.3+1.21-and-above
deps.accessories=1.0.0-beta.11+1.21
deps.cardinal-components-api=6.1.1

# Optional
deps.modmenu=11.0.1
deps.sodium=mc1.21-0.6.0-beta.2-fabric
